### PR TITLE
Couple of bugfixes from 'Gunslinger mod'

### PR DESCRIPTION
**Pull request by FreeZoneMods**
Fixes for some bugs of original engine. Initially found and fixed by Gunslinger mod team.

### CODE REVIEW

**Comment by revolucas** [comment]
Very generous. Thank you.

**Comment by revolucas** [comment]
`    const char* last_type = nullptr; 
    float w = 0, bs = 0;
    for (auto& c : m_magazine)
    {
        // Usually ammos in mag have same type, use it to improve performance
		if (last_type != c.m_ammoSect.c_str())
        {
			last_type = c.m_ammoSect.c_str();
            w  = pSettings->r_float(last_type, "inv_weight");
            bs = pSettings->r_float(last_type, "box_size");
        }
        res += w / bs;
    }`

This code can cause a crash in CIni:r_section because section can be null.

**Comment by Xottab-DUTY** [comment]
No one will be mind if it will be merge into other repos?

**Comment by FreeZoneMods** [comment]
Xottab-DUTY, of course, merge it. Gunslinger's team doesn't like bugs in projects, that's why the fixes were published :)

**Pull request merged**
